/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/layouts/ClassicalLayout/Aside.vue')['default']
    BlankLayout: typeof import('./src/components/layouts/BlankLayout/index.vue')['default']
    ClassicalLayout: typeof import('./src/components/layouts/ClassicalLayout/index.vue')['default']
    ElAvatar: typeof import('element-ui/lib/avatar')['default']
    ElBreadcrumb: typeof import('element-ui/lib/breadcrumb')['default']
    ElBreadcrumbItem: typeof import('element-ui/lib/breadcrumb-item')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElDropdown: typeof import('element-ui/lib/dropdown')['default']
    ElDropdownItem: typeof import('element-ui/lib/dropdown-item')['default']
    ElDropdownMenu: typeof import('element-ui/lib/dropdown-menu')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElLink: typeof import('element-ui/lib/link')['default']
    ElMenu: typeof import('element-ui/lib/menu')['default']
    ElMenuItem: typeof import('element-ui/lib/menu-item')['default']
    ElScrollbar: typeof import('element-ui/lib/scrollbar')['default']
    ElSubmenu: typeof import('element-ui/lib/submenu')['default']
    ElTag: typeof import('element-ui/lib/tag')['default']
    ElTooltip: typeof import('element-ui/lib/tooltip')['default']
    Header: typeof import('./src/components/layouts/ClassicalLayout/Header.vue')['default']
    IconJtMenuFold: typeof import('~icons/jt/menu-fold')['default']
    PageContent: typeof import('./src/components/layouts/ClassicalLayout/PageContent.vue')['default']
  }
}
